// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjY45F6sequ_uQxJ4vlnoow-2vEa5jlw',
    appId: '1:678465747831:web:cec6e6cc035e095a5cbf72',
    messagingSenderId: '678465747831',
    projectId: 'booknest-firebase',
    authDomain: 'booknest-firebase.firebaseapp.com',
    storageBucket: 'booknest-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCm4gYJseNi_WVIS9jsWvaaP3VoH1Rn0',
    appId: '1:678465747831:android:553898ff1c49543e5cbf72',
    messagingSenderId: '678465747831',
    projectId: 'booknest-firebase',
    storageBucket: 'booknest-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCS_isDXwguo8MayElnVnMfIU8SljzTc',
    appId: '1:678465747831:ios:fd2156fdf1c389115cbf72',
    messagingSenderId: '678465747831',
    projectId: 'booknest-firebase',
    storageBucket: 'booknest-firebase.firebasestorage.app',
    iosClientId: '678465747831-9c8jtqc0v3f2cmnsksf9f8q497gtq0pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCS_isDXwguo8MayElnVnMfIU8SljzTc',
    appId: '1:678465747831:ios:fd2156fdf1c389115cbf72',
    messagingSenderId: '678465747831',
    projectId: 'booknest-firebase',
    storageBucket: 'booknest-firebase.firebasestorage.app',
    iosClientId: '678465747831-9c8jtqc0v3f2cmnsksf9f8q497gtq0pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpjY45F6sequ_uQxJ4vlnoow-2vEa5jlw',
    appId: '1:678465747831:web:2f80e960d7d1589e5cbf72',
    messagingSenderId: '678465747831',
    projectId: 'booknest-firebase',
    authDomain: 'booknest-firebase.firebaseapp.com',
    storageBucket: 'booknest-firebase.firebasestorage.app',
  );

}